Bump develop/alt/roubaix
OpenSourcePolitics/osp-app pull request #128
Opened 2020-09-09 04:53 UTC by MoretS

Bump current 0.16 decidim version to develop version from BCN repo with new decidim modules enabled

- Feature added : Max number of vote per project on decidim-budgets module
https://github.com/armandfardeau/decidim/tree/feature/maximum-number-of-vote-per-project

2020-09-09 08:47 UTC, Quentinchampenois requested changes

2020-09-09 08:47 UTC, Quentinchampenois commented on Gemfile
> +gem "decidim", git: "https://github.com/armandfardeau/decidim", branch: "feature/maximum-number-of-vote-per-project"
Shall we not create an OpenSourcePolitics branch  ?

2020-09-09 08:47 UTC, Quentinchampenois commented on Gemfile
> +  gem "decidim-dev", git: "https://github.com/armandfardeau/decidim", branch: "feature/maximum-number-of-vote-per-project"
Shall we not create an OpenSourcePolitics branch ?

2020-09-09 08:47 UTC, Quentinchampenois commented on config/routes.rb
> +  mount LetterOpenerWeb::Engine, at: '/letter_opener' # if Rails.env.development?
Hi @MoretS, 

Is it necessary to keep the letter_opener route for production environment ?

```suggestion
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
```

2020-09-09 08:47 UTC, Quentinchampenois commented on lib/tasks/heroku.rake
>        puts "export SECRET_KEY_BASE=#{`bundle exe rake secret`}"
```suggestion
      puts "export SECRET_KEY_BASE=#{`bundle exec rake secret`}"
```

2020-09-09 10:09 UTC, armandfardeau requested changes
Fix the little issues and we are good to go

2020-09-09 10:09 UTC, armandfardeau commented on Gemfile
> +gem "decidim", git: "https://github.com/armandfardeau/decidim", branch: "feature/maximum-number-of-vote-per-project"
Yes we may.

2020-09-09 10:09 UTC, armandfardeau commented on Gemfile
> +  gem "decidim-dev", git: "https://github.com/armandfardeau/decidim", branch: "feature/maximum-number-of-vote-per-project"
+1

2020-09-15 09:20 UTC, armandfardeau approved these changes

2020-09-15 09:35 UTC, moustachu approved these changes

2020-10-26 11:01 UTC, Quentinchampenois approved these changes

2021-05-11 10:12 UTC, closed without merging